-- Per-marketplace parser settings for each Telegram user.
-- Execute in Supabase SQL Editor.

create table if not exists public.user_market_settings (
  id bigint generated by default as identity primary key,
  telegram_user_id text not null,
  marketplace text not null check (marketplace in ('avito', 'wb')),
  query text not null default 'iPhone',
  extra_keywords text not null default '',
  city text not null default 'moskva',
  min_price int not null default 0,
  max_price int not null default 0,
  memory text not null default '',
  color text not null default '',
  only_today boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (telegram_user_id, marketplace)
);

create or replace function public.set_user_market_settings_updated_at()
returns trigger as $$
begin
  new.updated_at = now();
  return new;
end;
$$ language plpgsql;

drop trigger if exists trg_user_market_settings_updated_at on public.user_market_settings;
create trigger trg_user_market_settings_updated_at
before update on public.user_market_settings
for each row execute function public.set_user_market_settings_updated_at();

-- Personal project mode: no RLS to simplify bot writes using anon key.
alter table public.user_market_settings disable row level security;
grant select, insert, update on public.user_market_settings to anon;

