-- Create users table for Telegram bot (anon-key insert)
-- Run in Supabase SQL editor.

create table if not exists public.users (
  id bigint generated by default as identity primary key,
  telegram_user_id text not null unique,
  telegram_username text,
  first_name text,
  last_name text,
  created_at timestamptz not null default now()
);

alter table public.users enable row level security;

-- Recreate policies (safe rerun)
drop policy if exists anon_insert_users on public.users;
drop policy if exists anon_update_users on public.users;

-- Ensure anon can insert/update (required alongside RLS policies)
grant insert, update on public.users to anon;

-- Allow anonymous inserts/updates when telegram_user_id is present
create policy anon_insert_users
  on public.users
  for insert
  to anon
  with check (telegram_user_id is not null);

create policy anon_update_users
  on public.users
  for update
  to anon
  using (telegram_user_id is not null)
  with check (telegram_user_id is not null);

-- TEMPORARY BYPASS (if RLS still blocks inserts unexpectedly)
-- After you confirm it works, you can remove/comment the next line and rely on policies.
alter table public.users disable row level security;

