-- Create users table for Telegram bot (anon-key insert)
-- Run in Supabase SQL editor.

create table if not exists public.users (
  id bigint generated by default as identity primary key,
  telegram_user_id text not null unique,
  telegram_username text,
  first_name text,
  last_name text,
  created_at timestamptz not null default now()
);

alter table public.users enable row level security;

-- Anonymous role still needs basic privileges besides RLS policies
grant insert, update on public.users to anon;

-- Allow anonymous inserts (bot uses anon key from server)
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_policies
    WHERE schemaname = 'public'
      AND tablename = 'users'
      AND policyname = 'anon_insert_users'
  ) THEN
    CREATE POLICY anon_insert_users
      ON public.users
      FOR INSERT
      TO anon
      WITH CHECK (telegram_user_id IS NOT NULL);
  END IF;

  IF NOT EXISTS (
    SELECT 1
    FROM pg_policies
    WHERE schemaname = 'public'
      AND tablename = 'users'
      AND policyname = 'anon_update_users'
  ) THEN
    CREATE POLICY anon_update_users
      ON public.users
      FOR UPDATE
      TO anon
      USING (telegram_user_id IS NOT NULL)
      WITH CHECK (telegram_user_id IS NOT NULL);
  END IF;
END $$;

