-- Stores metadata about generated Excel files on the server.
-- Execute in Supabase SQL editor.

create table if not exists public.excel_files (
  id bigint generated by default as identity primary key,
  telegram_user_id text,
  file_name text not null,
  file_path text not null unique,
  marketplace text,
  created_at timestamptz not null default now()
);

-- For this project we disable RLS to avoid blocking anon inserts.
alter table public.excel_files disable row level security;

-- Optional grants for clarity (won't matter if RLS is disabled).
grant insert, update on public.excel_files to anon;

