-- User parser settings (persisted profile per Telegram user)
-- Execute in Supabase SQL editor.

create table if not exists public.user_settings (
  id bigint generated by default as identity primary key,
  telegram_user_id text not null unique,
  marketplace_default text not null default 'avito',
  query text not null default 'iPhone',
  extra_keywords text not null default '',
  city text not null default 'moskva',
  min_price int not null default 0,
  max_price int not null default 0,
  memory text not null default '',
  color text not null default '',
  only_today boolean not null default false,
  seller_type text not null default 'any',
  min_rating numeric not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- Keep updated_at fresh on update
create or replace function public.set_user_settings_updated_at()
returns trigger as $$
begin
  new.updated_at = now();
  return new;
end;
$$ language plpgsql;

drop trigger if exists trg_user_settings_updated_at on public.user_settings;
create trigger trg_user_settings_updated_at
before update on public.user_settings
for each row execute function public.set_user_settings_updated_at();

-- For this personal project, disable RLS to simplify bot writes with anon key.
alter table public.user_settings disable row level security;
grant select, insert, update on public.user_settings to anon;

