-- Автопарсинг Wildberries: расписание, флаг базы, учёт виденных карточек.
-- Выполнить в Supabase SQL Editor после остальных миграций.

create table if not exists public.wb_autoparse_state (
  telegram_user_id text primary key,
  interval_minutes int not null default 30 check (interval_minutes >= 5 and interval_minutes <= 180),
  enabled boolean not null default true,
  is_running boolean not null default false,
  baseline_ready boolean not null default false,
  settings_fingerprint text not null default '',
  last_run_started_at timestamptz,
  last_run_finished_at timestamptz,
  last_run_ok boolean,
  next_scheduled_at timestamptz,
  updated_at timestamptz not null default now()
);

create or replace function public.set_wb_autoparse_updated_at()
returns trigger as $$
begin
  new.updated_at = now();
  return new;
end;
$$ language plpgsql;

drop trigger if exists trg_wb_autoparse_state_updated on public.wb_autoparse_state;
create trigger trg_wb_autoparse_state_updated
before update on public.wb_autoparse_state
for each row execute function public.set_wb_autoparse_updated_at();

create table if not exists public.wb_seen_listings (
  id bigint generated by default as identity primary key,
  telegram_user_id text not null,
  listing_id text not null,
  created_at timestamptz not null default now(),
  unique (telegram_user_id, listing_id)
);

create index if not exists idx_wb_seen_listings_user on public.wb_seen_listings (telegram_user_id);

alter table public.wb_autoparse_state disable row level security;
alter table public.wb_seen_listings disable row level security;

grant select, insert, update, delete on public.wb_autoparse_state to anon;
grant select, insert, update, delete on public.wb_seen_listings to anon;
