-- Create users table for Telegram bot (anon-key insert)
-- Run in Supabase SQL editor.

create table if not exists public.users (
  id bigint generated by default as identity primary key,
  telegram_user_id text not null unique,
  telegram_username text,
  first_name text,
  last_name text,
  created_at timestamptz not null default now()
);

alter table public.users enable row level security;

-- Allow anonymous inserts (bot uses anon key from server)
create policy if not exists "anon_insert_users"
on public.users
for insert
to anon
with check (telegram_user_id is not null);

-- Allow updates needed for "resolution=merge-duplicates"
create policy if not exists "anon_update_users"
on public.users
for update
to anon
using (telegram_user_id is not null)
with check (telegram_user_id is not null);

